# Generated by Django 2.1.3 on 2018-11-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20181129_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product', upload_to=''),
            preserve_default=False,
        ),
    ]
