# Generated by Django 2.1.3 on 2018-11-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
