# Generated by Django 3.0.1 on 2020-04-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='outer'),
            preserve_default=False,
        ),
    ]
